### ISSUE TITLE
Consistent management of public apis in our deliverables

### ISSUE THREAD

**Issue by quentinderoubaix** [AmadeusITGroup/AgnosUI#294]
## Current situation
We provide services / utils / components and so on by exporting everything in a single index file in each project.
Sometimes we also import core files from lib projects (so a 2-layer jump).

## Proposed architecture
We propose with this issue to restructure our code base to avoid barrel files, properly control what is our public api and consistently structure our code / deliveries between the core, headless and lib projects.
This consistency, once finished, will also be useful when documenting everything that AgnosUI is offering.

The proposed structure of a delivery / code base is:
* a sub-folder **components** with all the components
* a sub-folder with all the **services**. a service is a reactive factory that defines logic that can be used with our without components
* a sub-folder **transitions** inside of **services** containing all transitions
* a sub-folder **utils**
* a file **types** with the types
* a file **slot** exporting the slot implementation for a particular framework
* a file **config** with the global config

## Tasks

- [x] Restructure the core following the above architecture
- [x] Restructure of the headless and lib projects *depends on previous task*
- [x] Update all imports and delete all index files *depends on previous task*
- [x] Add linters to enforce that imports should always be one-level down and use suffixes
- [ ] Automatic generation of entry points, based on a naming convention *should probably be done after task 2*
- [ ] Ensure no regression of public apis using a guard system (inspiration from angular golden files)
- [x] Ensure in the PR build that the demos are using the dist folders
- [x] Automatize re-exports of down layers (especially for services, utils and transitions)
